### ISSUE TITLE
As a user, with my wallet connected, I can browse my hypercerts

### ISSUE THREAD

**Issue by reasn** [Network-Goods/hypercerts-docs#15]
## Requirements
* The user is asked to connect their wallet if it's not connected
* Gallery view
* Top navigation contains links to "split" and "merge" pages
* Burned hypercerts are shown on the bottom below a horizontal ruler
* Hypercerts are sorted descendingly by last operation

**Comment by Jipperism** [comment]
- [ ] Add `Fraction` entity to the graph

**Comment by Jipperism** [comment]
- [ ] The user is asked to connect their wallet if it's not connected
- [ ] Gallery view
- [ ] Top navigation contains links to "split" and "merge" pages
- [ ] Burned hypercerts are shown on the bottom below a horizontal ruler
- [ ] Hypercerts are sorted descendingly by last operation
