### ISSUE TITLE
As a user, I can merge fractions of a hypercert

### ISSUE THREAD

**Issue by reasn** [Network-Goods/hypercerts-docs#17]
## Requirements
* I can only merge fractions that I own
* I can only merge fractions of the same hypercert
* Merge is its own view on the UI (see [Wireframes](https://www.figma.com/file/HxdY1EowSYHL2vXOxIGkKv/Hypercerts-Milestone-2-(Draft!)))
* I get meaningful, actionabe error messages when something goes wrong

**Comment by Jipperism** [comment]
## Contract
- [ ] Add `merge` function to contract, which accepts a list of fraction ids as it's argument and returns the id of the fraction they all got merged into

## App
- [ ] Add merge all my fractions button to fraction list
