### ISSUE TITLE
As a user, when minting, I can enter fraction sizes

### ISSUE THREAD

**Issue by reasn** [Network-Goods/hypercerts-docs#19]
## Requirements
* Text area with each line representing a fraction
* Total of fractions is units to be minted
* Minter is owner of all the fractions
* We explain the relationship of units, fractions, and hypercerts
* Fractions are clearly indicated as optional to keep the UX simple
* We nudge the user in the UI
  * We recommend minting 100 units (percent).
  * We nudge users into limiting the amount of fractions, telling them that every fraction will be visible on OpenSea
* Users get meaningful, actionable error messages when something goes wrong

## Technical
Referencing ERC3525
* Hypercert is slot
* Fraction is token
* `mint()` receives an uint8[] expressing the fragments. The total of the fragment is `totalUnits`. For every fragment, a token is minted in the same slot. 
** `slotID` is `hypercertID`
** `tokenID` is `fragmentID`

## Contract

- [ ]  https://github.com/protocol/hypercerts-protocol/pull/40

## Graph

- [ ] #23

## App

- [ ] #24

**Comment by Jipperism** [comment]
[ ] Add available units to Hypercert entity in the graph

**Comment by bitbeckers** [comment]
@reasn "We explain the relationship of units, fractions, and hypercerts" -> Would we need some copy?

**Comment by moconnell** [comment]
@reasn @holkeb as part of the ERC-3525 spec (inherited from ERC-721), we can define the symbol for hypercerts; what would like this to be?

**Comment by holkeb** [comment]
First choice would be "HYP", but as this is already taken as far as I know, let's go with "HYPC"

Or do you have other suggestions?

**Comment by moconnell** [comment]
Looks like they are both taken, as is CERT.

What about HCRT? Not returning anything on coinmarketcap..

**Comment by holkeb** [comment]
Hmm, also available HYCE. That and HCRT are both not my first choice, but both would work.

Lets go with HYCE. (except someone has differing strong opinions here)

**Comment by moconnell** [comment]
Ok, also as part of the contract spec, we should return contract-level metadata (as well as for slot and token - we already discussed those):

```
{
  "title": "Contract Metadata",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Contract Name"
    },
    "description": {
      "type": "string",
      "description": "Describes the contract"
    },
    "image": {
      "type": "string",
      "description": "Optional. Either a base64 encoded imgae data or a URI pointing to a resource with mime type image/* representing what this contract represents."
    },
    "external_link": {
      "type": "string",
      "description": "Optional. A URI pointing to an external resource."
    },
    "valueDecimals": {
      "type": "integer",
      "description": "The number of decimal places that the balance should display - e.g. 18, means to divide the token value by 1000000000000000000 to get its user representation."
    }
  }
}
```

So, fill in the blanks/correct as desired here pls..

name: Hypercerts
description: ??
image: ??
external_link: ??
valueDecimals: 0
