### ISSUE TITLE
As a user, I want the image of my hypercert to inform me of its content

### ISSUE THREAD

**Issue by bitbeckers** [Network-Goods/hypercerts-docs#25]
## SVG integration
  * Based on the data of the hypercert a SVG is generated that is included as the default picture
  * Users can replace this picture and upload any picture  ❓  is this true?
  * (future version) Users can choose between different algorithms to generate the SVG

## Technical

- [x] #26
- [x] #27

**Comment by bitbeckers** [comment]
@holkeb @reasn :
> Users can replace this picture and upload any picture

That's not the case right? We're going with SVG generated with on-chain data?

**Comment by holkeb** [comment]
I would enable this feature in general. Use case: Someone wants to create artwork connected to the hypercert. That would be ok.

If for a specific use case, we could restrict this on the front-end. E.g. if on AI safety we want that all hypercerts look the same.
