### ISSUE TITLE
Add SVG generation contract and generate one SVG based on hypercert data

### ISSUE THREAD

**Issue by bitbeckers** [Network-Goods/hypercerts-docs#26]
- [x] Add Hypercert_SVG contract
- [x] Couple Minter-SVG contract
- [x] Generate SVG filled with content from impact claim
- [x] SVG string testing (string format, content, etc)
- [x] Add SVG to tokenURI/slotURI returned by minter contract
- [x] Validate generated SVG

**Comment by bitbeckers** [comment]
<img width="347" alt="Screenshot 2022-09-29 at 16 21 25" src="https://user-images.githubusercontent.com/19667964/193057172-eb79dad4-3cc4-4edf-b138-6a10fe08bde5.png">

@reasn @holkeb regarding the value '50/100' that probably won't work for hypercerts with high-numbers. Would you think a percentage is more scalable?

**Comment by holkeb** [comment]
@bitbeckers

1. Yes, a percentage is actually preferred 
2. Yes, "Research on Infra-Baesianism" is the title and I think we need to limit it in length. I assume we need to limit all fields in length, right? Only exception is the date. Even the percentage could theoretically be too long, ie 0,000000000000000001%, so I would even limit that (just in case)
3. "AI Existential Safety" is the Scope of Impact

**Comment by bitbeckers** [comment]
>     2. Yes, "Research on Infra-Baesianism" is the title and I think we need to limit it in length. I assume we need to limit all fields in length, right? Only exception is the date. Even the percentage could theoretically be too long, ie 0,000000000000000001%, so I would even limit that (just in case)

My proposal would be a percentage up to two decimals: 100,00%

>     3. "AI Existential Safety" is the Scope of Impact

What is there are multiple scopes of impact? We've built and tested for that, is that not needed? Or otherwise, how to select which one on, or which ones, are displayed?

**Comment by holkeb** [comment]
Yes, percentage up to two decimals works. For all use cases that I have in mind this will be ok.

I would concatenate the multiple scopes of impact with a comma in between and then enforce a limit in length. Do we store the multiple scope of impact in the order that the user entered them? If so, that would be my preferred order.

**Comment by bitbeckers** [comment]
Ok in that case it would be:
* user submits scopes of impact, we store and Array[1,2,3,4,...]
* we generate SVG and use max 3 values, where the string is cut of to meet the dimensions of the SVG

For example the scopes of impact would look like:
- AI Alignment research
- Image classifications for the protect....
- Education

**Comment by holkeb** [comment]
Sounds good, except that makes the data structure in any way weird.

And with the chance of making it more complicated. Something that I have in my mind for later, but maybe it is relevant if you turn the scope of impact into an array:

At some point we might want to add an impact metric, e.g. "tons of CO2e reduced" or "hours of mentorship to high-school students". We could just have a separate variable to store this, but we could also use the scopes of impact, e.g. if the scope of impact is "CO2e reduction in tons" then we could store a quantity with it. Bringing this up because this would then just go into the array, right? Let me know if I'm complicating things too much here now :)

**Comment by bitbeckers** [comment]
Ehm yeah it already is an array, that enables users to provides the multiple scopes as the app supports now. What you're describing in the simples form is easy:
certId -> scopeId -> value

The crux is preventing noisy or impossible data. For instance Elephants saved -> 100000. But, since there are evaluators the alarming for weird input could be front-end logic, the rest is up to the user, evaluator and funder

**Comment by holkeb** [comment]
Yes, I would like @davidad's quick input on this, but I think I would enable it on the protocol level and then shift the burden to front-end and evaluators

**Comment by holkeb** [comment]
Update: We leave the impact metrics to the evaluation, i.e. if someone wants to claim a specific quantitative impact, it would be a self-evaluation.

**Comment by bitbeckers** [comment]
![Image](https://user-images.githubusercontent.com/19667964/194144702-4f4de9c2-f7d3-4397-87ed-d28ce99ee189.png)


The is a cert generated with on chain-data taking into account the updated fonts but more important a name that's long ("TestSVG one two three four five six seven eight") and multiple workscopes (cut-off for first 3). 

@holkeb I would say this matches our needs for now, what do you think?

**Comment by holkeb** [comment]
Cool! That looks very nice, thank you

I think I wasn't in the room when the latest design of the SVGs where discussed. In [figma](https://www.figma.com/file/HxdY1EowSYHL2vXOxIGkKv/Hypercerts-Milestone-2-(Draft!)?node-id=0%3A1) on the right from the design that you build here, we switched some categories: 
Top --> Scope of Impact
Below name --> Contributors
Bottom --> Time of work

I hope this didn't get lost in the communication. If so, and it is lots of work to change, please let me know.

On the name, yes, that is what I had in mind :) I only wonder if we could get a few more characters shown? (e.g. by limiting the text below the name to two lines and adding a fourth line for the name)

**Comment by bitbeckers** [comment]
Sorry I missed this last note. For reference and whatnot, this is what we'll deploy now

<img width="564" alt="Screenshot 2022-10-13 at 12 53 23" src="https://user-images.githubusercontent.com/19667964/195578319-a93b538c-9f66-427a-aea5-ca100de0773f.png">
